# Generated by Django 5.0 on 2023-12-26 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(max_length=255, null=True)),
                ('cat_image', models.ImageField(null=True, upload_to='photos/categories')),
            ],
        ),
        migrations.AlterField(
            model_name='category',
            name='cat_image',
            field=models.ImageField(null=True, upload_to='photos/categories'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
