# Generated by Django 5.0 on 2023-12-26 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_brand_alter_category_cat_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PRODUCT_BY',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SELLER',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='warranty_period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(max_length=255, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='brand',
            name='cat_image',
        ),
    ]
